module.exports = {
  TestUrl: process.env.TEST_E2E_URL || 'https://manage-case.aat.platform.hmcts.net/',
  TestEnv: process.env.RUNNING_ENV || 'aat',
  TestShowBrowserWindow: process.env.SHOW_BROWSER_WINDOW || true,
  TestRetryFeatures: 0,
  TestRetryScenarios: process.env.RETRY_SCENARIOS || 0,
  TestPathToRun: process.env.E2E_TEST_PATH || 'tests/solicitorCreateCase.test.js',
  TestOutputDir: process.env.E2E_OUTPUT_DIR || './functional-output/xui',
  TestEnvSolUser: 'TEST_SOLICITOR@mailinator.com',
  TestEnvSolPassword:'genericPassword123',
  TestEnvCWUser: 'TEST_CASE_WORKER_USER@mailinator.com',
  TestEnvCWPassword: 'genericPassword123',
  TestEnvCourtAdminUser:'DivCaseWorkerUser@AAT.com',
  TestEnvCourtAdminPassword:'DivPassword1234',
  TestEnvProfUser: process.env.PROF_USER_EMAIL || '',
  TestEnvProfPassword: process.env.PROF_USER_PASSWORD || '',
  TestForXUI: process.env.TESTS_FOR_XUI_SERVICE === 'true',
  TestForAccessibility: process.env.TESTS_FOR_ACCESSIBILITY === 'true',
  TestForCrossBrowser: process.env.TESTS_FOR_CROSS_BROWSER === 'true',
  TestIdamClientSecret: process.env.IDAM_CLIENT_SECRET === 'thUphEveC2Ekuqedaneh4jEcRuba4t2t',
  TestS2SAuthSecret: process.env.SERVICE_SECRET || ''
};
